%YAML:1.0
num_classes:3
model: "/home/codes/caffe_inference/models/car.prototxt"
weight: "/home/codes/caffe_inference/models/car.caffemodel"
mean:
   - 1.029801e02
   - 1.159465e02
   - 1.227717e02
scale: 32
size_min: 640
size_max: 2000
score_nms: 0.4
score_obj: 0.4
