%YAML:1.0
# 29, 25, 34,34,34,34,37
num_classes: 227
model: "/home/codes/caffe_inference/models/plate/model.prototxt"
weight: "/home/codes/caffe_inference/models/plate/weights.caffemodel"
input_width: 256
input_height: 64
mean:
   - 0.0e0
   - 0.0e0
   - 0.0e0

province:
   - "浙"
   - "粤"
   - "京"
   - "津"
   - "冀"
   - "晋"
   - "蒙"
   - "辽"
   - "黑"
   - "沪"
   - "吉"
   - "苏"
   - "皖"
   - "赣"
   - "鲁"
   - "豫"
   - "鄂"
   - "湘"
   - "桂"
   - "琼"
   - "渝"
   - "川"
   - "贵"
   - "云"
   - "藏"
   - "陕"
   - "甘"
   - "青"
   - "新"

city_code:
   - "A"
   - "B"
   - "C"
   - "D"
   - "E"
   - "F"
   - "G"
   - "H"
   - "J"
   - "K"
   - "L"
   - "M"
   - "N"
   - "O"
   - "P"
   - "Q"
   - "R"
   - "S"
   - "T"
   - "U"
   - "V"
   - "W"
   - "X"
   - "Y"
   - "Z"

serial_no:
   - "0"
   - "1"
   - "2"
   - "3"
   - "4"
   - "5"
   - "6"
   - "7"
   - "8"
   - "9"
   - "A"
   - "B"
   - "C"
   - "D"
   - "E"
   - "F"
   - "G"
   - "H"
   - "J"
   - "K"
   - "L"
   - "M"
   - "N"
   - "P"
   - "Q"
   - "R"
   - "S"
   - "T"
   - "U"
   - "V"
   - "W"
   - "X"
   - "Y"
   - "Z"   

serial_no_last:
   - "0"
   - "1"
   - "2"
   - "3"
   - "4"
   - "5"
   - "6"
   - "7"
   - "8"
   - "9"
   - "A"
   - "B"
   - "C"
   - "D"
   - "E"
   - "F"
   - "G"
   - "H"
   - "J"
   - "K"
   - "L"
   - "M"
   - "N"
   - "P"
   - "Q"
   - "R"
   - "S"
   - "T"
   - "U"
   - "V"
   - "W"
   - "X"
   - "Y"
   - "Z"
   - "学"
   - "港"
   - "澳"


